### ISSUE TITLE
Pending promises when using line numbers

### ISSUE THREAD

**Issue by mattcroat** [shikijs/shiki-magic-move#11]
The issue from #8 is back when using line numbers — the transition never starts for tokens that don't change, and thus never resolves.

https://github.com/shikijs/shiki-magic-move/assets/38083522/f2fc6e98-3990-424d-a72a-6c668abcb286

The `promises` log from `shiki-magic-move` shows the unresolved promises.

![image](https://github.com/shikijs/shiki-magic-move/assets/38083522/6b26e031-3745-4050-967b-22b8a60df35c)

This is confirmed when you unfold the pending promises, and see they're the tokens that don't change.

![image](https://github.com/shikijs/shiki-magic-move/assets/38083522/f180dad2-4da6-42ea-9329-2b8c4e23d0ab)

**Comment by paoloricciuti** [comment]
I think i found a solution for this that involves `element.getAnimations()` will try to experiment later
