### ISSUE TITLE
Multiple lines of jsx code renders slowly

### ISSUE THREAD

**Issue by wood3n** [shikijs/shiki-magic-move#22]
Hi, I use it in react, it will be slowly when change multiple lines of code, do you have some advice to improve this?

[![Edit shiki-magic-move-sample](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/shiki-magic-move-sample-9jdnlg)

![move-sample](https://github.com/user-attachments/assets/bb05977b-ac33-469e-8a7e-669eba6bdab6)

**Comment by hxj0x** [comment]
似乎是这个[提交](https://github.com/shikijs/shiki-magic-move/pull/18)导致的，`getAnimations`特别耗时，我暂时固定到`0.4.2`版本
